fix issue of the extension no longer working after screen lock and then unlock is done.
thomkeh/gnome-shell-force-application-view pull request #1
Opened 2018-07-19 14:56 UTC by goodwillcoding

Hi,

Like your extension it does a good job. However, it stops working after screen lock and unlock is done. I tracked down the issue and fixed it. I included comments in the code to explain the issue. Also I renamed variables to be a tad more readable.

I am hoping you can merge the code in and post the updated extension.

As a note your extension and the one by fawtytoo (https://extensions.gnome.org/extension/1337/show-applications-instead-of-overview/) have nearly the same code, however I could not find his in any place I can submit a PR to. And it seems silly to create yet a third extension.

Let me know if you have any questions.

2018-07-19 15:37 UTC, thomkeh commented
Hi!

I'm glad someone else found it useful. Your changes look good! I wrote it simply as a quick-and-dirty script.

I can definitely merge your PR. However, I'm actually not using GNOME anymore at the moment (had to switch to MacOS for work...). So, do you maybe want to take over the extension? I don't think I can transfer the ownership of the extension on extensions.gnome.org, so you would have to add a new one. But I could link to your extension in the description of mine.

I can transfer this repository to your Github account if you want.

What do you think?

2018-07-19 15:47 UTC, tmke8 requested changes
I think there is a wrong variable name.

2018-07-19 15:47 UTC, thomkeh commented on start-overlay-in-application-view@cis.net/extension.js
> +    nativeToggleFunction = Overview.Overview.prototype['toggle'];
I think it should be `originalToggleFunction`?

2018-07-19 15:47 UTC, thomkeh commented on start-overlay-in-application-view@cis.net/extension.js
> +          and unhides. We need to look into "_animateVisible"
I remember that problem. Never knew why it happened

2018-07-19 15:47 UTC, thomkeh commented on start-overlay-in-application-view@cis.net/extension.js
> +    if have the original function, put it back to back and re-bind the
"if **we** have"?

2018-07-19 15:47 UTC, thomkeh commented on start-overlay-in-application-view@cis.net/metadata.json
> +  "description": "When pressing activating overview, the application view is shown instead of the view with the windows.",
"When ~~pressing~~ activating overview"?

2018-07-20 02:07 UTC, goodwillcoding commented
@thomkeh I fixed everything you asked in the code review.

On overall I am fine taking over the extensions, but it would be nice not to have yet a 3rd one on the EGO site. Can you look if it is possible to change email/username.

2018-07-22 11:27 UTC, merged

2018-07-22 12:17 UTC, thomkeh commented
I just looked again and I don't see any setting to change the email address of the account (just the password). I can however remove the extension from the site. I could do that after yours is up.

2018-07-22 16:33 UTC, goodwillcoding commented
I am thinking we can do the following:
1. grant me commit rights to this repo so I can push to master
2. change the password on the ego site and let me know what it is and I will handle the extension from now on. (I know the review process will send emails but I can just as well check the review site for feedback anyhow). You will still have control of the email so you can always take it away.
3. I took look at the Django codebase of the EGO site and I am thinking of send Gnome people a PR for email change (that might be a longer affair).

This way you do not have to do much but filter the email from the ego site and there is less sadness cause of yet a 3rd extension. If that's too much we can do the 3rd extension round.